### ISSUE TITLE
"Add Material Properties" has a global effect / renames all materials

### ISSUE THREAD

**Issue by ikonnow** [brickengineer/BCRYExporter#1]
**Issue description:**
Add Bcry exporter material properties to materials changes the material name for ALL nodes / meshes (collection-wide).

**Steps to reproduce:**
Click on node, in Material Utilities click on "Add Material Properties", then a global name change happens. In the screenshot the same material was assigned and renamed for Cube and Cube.001 ect, which makes this wonderful feature unfortunately only very limited applicable.

**Intended behavior:**
Ideally, as announced in the info text, a change of the material properties should only happen for the SELECTED node.
When selected for:
- the selected collection. 
- the selected mesh
- the selected submesh
![image](https://user-images.githubusercontent.com/25803775/156560146-5ebaf498-622c-46a0-98cf-284b31d2e453.png)
The hover over info text should be: Add material properties to the materials of the selected node

**Comment by brickengineer** [comment]
Thanks for your feedback. This issue have been solved now.
However I didn't take your `Intended Behavior` list because the design logic doesn't meet the function's initial purpose. For more explanation, please visit the commit message at https://github.com/brickengineer/BCRYExporter/commit/da99d3ffc20ca8f79ded3893bb4bb1e3254988e3
I'd appreciate it if you could let me know if the updated function meets your needs.

**Comment by ikonnow** [comment]
Tested, works fine...!
